# Generated by Django 5.1.7 on 2025-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('achievement_type', models.CharField(choices=[('PROJECT', 'Project'), ('CERTIFICATE', 'Certificate'), ('BADGE', 'Badge')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_achieved', models.DateField()),
                ('badge_image', models.URLField(blank=True, null=True)),
                ('certificate_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('display_image', models.URLField(blank=True, help_text='Image to display for certificates/projects', null=True)),
            ],
            options={
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text="Font Awesome class (e.g., 'fab fa-python')", max_length=50)),
                ('skill_type', models.CharField(choices=[('LANG', 'Programming Languages'), ('FRAM', 'Frameworks'), ('TOOL', 'Tools'), ('ADD', 'Additional Skills')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['skill_type', 'name'],
            },
        ),
    ]
