# Generated by Django 5.1.4 on 2025-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text="Font Awesome class (e.g., 'fab fa-python')", max_length=50)),
                ('skill_type', models.CharField(choices=[('LANG', 'Programming Languages'), ('FRAM', 'Frameworks'), ('TOOL', 'Tools'), ('ADD', 'Additional Skills')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['skill_type', 'name'],
            },
        ),
    ]
