# Generated by Django 5.1.7 on 2025-03-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_achieved', models.DateField()),
                ('category', models.CharField(choices=[('PROJECT', 'Project'), ('CERTIFICATE', 'Certificate')], max_length=20)),
                ('certificate_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_achieved'],
            },
        ),
    ]
