# Generated by Django 5.1.7 on 2025-03-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_achievement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
