# Generated by Django 5.1.7 on 2025-03-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('achievement_type', models.CharField(choices=[('PROJECT', 'Project'), ('CERTIFICATE', 'Certificate'), ('BADGE', 'Badge')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_achieved', models.DateField()),
                ('badge_image', models.URLField(blank=True, null=True)),
                ('certificate_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('display_image', models.URLField(blank=True, help_text='Image to display for certificates/projects', null=True)),
            ],
            options={
                'ordering': ['-date_achieved'],
            },
        ),
    ]
